"""Jev integration: one `system_one` call per tick per vif.

The call fans out every question over the same state: a Choice over the
activity catalog, two Scores (intensity, interactivity) and four Nouls
(just_started, just_ended, automated, someone_is_typing). Jev only maps the
described shape to answers; nothing here does arithmetic on its output.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field

from typesafe_sdk import AsyncTypeSafeClient, Choice, Noul, Score, RetryPolicy

from .catalog import Activity, criteria
from .config import MODEL, PREVIOUS_TOP_K

log = logging.getLogger("netprofiler.jev")

INTENSITY_LEVELS = [
    "Link is idle or nearly silent: negligible volume, long idle gaps, no bursts",
    "Light background chatter: low volume in brief sporadic bursts",
    "Moderate steady use: intermittent or mostly active with moderate volume",
    "Heavy sustained transfer: high volume, continuously active, long bursts",
    "Saturating the link: very high volume of MTU-sized packets back-to-back with no gaps",
]

INTERACTIVITY_LEVELS = [
    "Fully automated: machine-like even pacing or periodic checks, no human rhythm at all",
    "Mostly automated with an occasional human trigger such as a single click starting a transfer",
    "Mixed: some bursts follow human pauses, others run on their own",
    "Human-paced: bursts and pauses follow clicks, scrolls and reading time",
    "Tight real-time human interaction: keystroke-like or click-like rhythm answered immediately",
]

NOUL_QUESTIONS = {
    "just_started": Noul(
        instructions="Has a new activity just begun in this window compared with the previous window?",
        criteria={
            "true": "Trend words say volume, flows or packet rate started from nothing or rose sharply, and the previous top answers differ from what the shape now suggests",
            "false": "The shape continues the previous window's activity or stays quiet",
        },
    ),
    "just_ended": Noul(
        instructions="Has an activity that was under way in the previous window just ended?",
        criteria={
            "true": "Trend words say volume or packet rate dropped to nothing or fell sharply and the link is now silent or sporadic while the previous top answers were an active activity",
            "false": "Activity continues, or the link was already quiet before",
        },
    ),
    "automated": Noul(
        instructions="Is this traffic generated by software running on its own, without a person acting right now?",
        criteria={
            "true": "Machine-like even pacing, periodic checks, or sustained transfer with no human rhythm",
            "false": "Bursts and pauses follow a human rhythm: keystroke-like, click-like, or reading pauses",
        },
    ),
    "someone_is_typing": Noul(
        instructions="Is a person typing right now?",
        criteria={
            "true": "Tiny outbound packets at a keystroke-like uneven human rhythm, each answered by a tiny reply",
            "false": "No keystroke-like cadence; packets are larger, machine-paced, or absent",
        },
    ),
}


ACTIVITY_INSTRUCTIONS = {
    "question": "Which catalogued activity best explains the traffic in the state?",
    "input": (
        "The state is either a prose description of traffic shape in level words, or a headers-only packet log "
        "with a summary line, a flow table and per-packet lines. Read whichever form is present."
    ),
    "focus": "Judge from shape: how many flows and endpoints, how long they live, direction, burst structure, packet sizes, inter-arrival rhythm, idle gaps.",
    "tie_breaks": [
        "Many flows to many endpoints active at once with bytes spread across them is torrent, even when the volume is high; a single dominant flow is a download or upload.",
        "A burst of many new short-lived flows to several endpoints followed by seconds of quiet is web browsing, even when the burst moves a lot of data; a few flows fetching file after file without pauses is software updates.",
        "One or a few long-lived flows of tiny packets with a keystroke-like uneven cadence is ssh. A single flow that wakes every few seconds for a short rapid exchange of medium-sized packets and is otherwise sporadic is wallet polling rpc. A single flow that is almost silent, with at most one tiny burst per window and machine-like regular keepalives, is chat, not idle: idle has no flow at all.",
    ],
    "continuity": "Previous top answers may be given; keep the same answer when the traffic has not meaningfully changed, switch when it has.",
}


def build_questions(catalog: list[Activity], raw: bool = False) -> dict:
    """The same questions for every mode (question set v3, see tools/questions)."""
    instructions = ACTIVITY_INSTRUCTIONS
    return {
        "activity": Choice(instructions=instructions, criteria=criteria(catalog)),
        "intensity": Score(instructions="How intense is the traffic on this link?", criteria=INTENSITY_LEVELS),
        "interactivity": Score(instructions="How much does the traffic timing follow a person's actions?", criteria=INTERACTIVITY_LEVELS),
        **NOUL_QUESTIONS,
    }


@dataclass
class Answer:
    """Typed answers for one tick, straight from the response."""

    probabilities: dict[str, float]  # activity key -> p
    top: str
    confidence: float
    intensity: float  # 0..1 (score / top level)
    interactivity: float  # 0..1
    nouls: dict[str, float]
    latency_s: float
    input_tokens: int | None = None


@dataclass
class PreviousTop:
    entries: list[tuple[str, float]] = field(default_factory=list)

    def as_state(self, catalog_by_key: dict[str, Activity]) -> list[dict[str, str]]:
        """Previous top answers as level words, no numbers."""
        out = []
        for key, p in self.entries[:PREVIOUS_TOP_K]:
            name = catalog_by_key[key].name if key in catalog_by_key else key
            if p >= 0.7:
                strength = "strong"
            elif p >= 0.4:
                strength = "likely"
            elif p >= 0.15:
                strength = "possible"
            else:
                strength = "faint"
            out.append({"activity": name, "strength": strength})
        return out


class JevClient:
    """Async wrapper enforcing at most one in-flight request per vif."""

    def __init__(self, api_key: str, catalog: list[Activity], model: str = MODEL, timeout: float = 8.0, raw: bool = False, raw_ips: bool = False) -> None:
        self._client = AsyncTypeSafeClient(api_key=api_key, model=model, timeout=timeout, retry=RetryPolicy(max_retries=1))
        self.raw = raw
        self.raw_ips = raw_ips
        self._questions = build_questions(catalog, raw=raw)
        self._catalog_by_key = {a.key: a for a in catalog}
        self._busy: set[str] = set()
        self.dropped: dict[str, int] = {}

    async def close(self) -> None:
        await self._client.aclose()

    def is_busy(self, vif: str) -> bool:
        return vif in self._busy

    def build_state(self, shape_text: str, previous: PreviousTop) -> dict:
        """Exactly what Jev receives as `state`; the questions are static."""
        if getattr(self, "raw", False):
            from .rawcap import RAW_LEGEND, RAW_LEGEND_IPS

            return {
                "legend": RAW_LEGEND_IPS if getattr(self, "raw_ips", False) else RAW_LEGEND,
                "packet_log": shape_text,
                "previous_batch_top_answers": previous.as_state(self._catalog_by_key) or "none yet",
            }
        return {
            "traffic_shape": shape_text,
            "previous_window_top_answers": previous.as_state(self._catalog_by_key) or "none yet",
        }

    def questions_json(self) -> dict:
        return {k: q.model_dump(exclude_none=True) for k, q in self._questions.items()}

    async def ask(self, vif: str, state: dict) -> Answer | None:
        """Return None if a call for this vif is already outstanding (tick dropped)."""
        if vif in self._busy:
            self.dropped[vif] = self.dropped.get(vif, 0) + 1
            return None
        self._busy.add(vif)
        try:
            t0 = time.monotonic()
            resp = await self._client.system_one(state=state, questions=self._questions)
            latency = time.monotonic() - t0
            a = resp.answers
            choice = a["activity"]
            inten = a["intensity"]
            inter = a["interactivity"]
            return Answer(
                probabilities=dict(choice.probabilities),
                top=choice.choice,
                confidence=choice.confidence,
                intensity=inten.score / max(1, len(INTENSITY_LEVELS) - 1),
                interactivity=inter.score / max(1, len(INTERACTIVITY_LEVELS) - 1),
                nouls={k: a[k].noul for k in NOUL_QUESTIONS},
                latency_s=latency,
                input_tokens=getattr(resp.usage, "input_tokens", None),
            )
        finally:
            self._busy.discard(vif)


class FakeJevClient:
    """Offline stand-in for --dry-run: returns a flat-ish distribution so the
    UI and accounting can be exercised without network access."""

    def __init__(self, catalog: list[Activity], raw: bool = False, raw_ips: bool = False) -> None:
        self._keys = [a.key for a in catalog]
        self._catalog_by_key = {a.key: a for a in catalog}
        self.raw = raw
        self.raw_ips = raw_ips
        self._questions = build_questions(catalog, raw=raw)
        self._busy: set[str] = set()
        self.dropped: dict[str, int] = {}
        self._i = 0

    build_state = JevClient.build_state
    questions_json = JevClient.questions_json

    async def close(self) -> None:
        return None

    def is_busy(self, vif: str) -> bool:
        return vif in self._busy

    async def ask(self, vif: str, state: dict) -> Answer | None:
        if vif in self._busy:
            self.dropped[vif] = self.dropped.get(vif, 0) + 1
            return None
        self._busy.add(vif)
        try:
            await asyncio.sleep(0.05)
            self._i += 1
            n = len(self._keys)
            top = self._keys[(self._i // 5) % n]
            probs = {k: 0.3 / n for k in self._keys}
            probs[top] += 0.7
            shape_text = state.get("traffic_shape") or state.get("packet_log") or ""
            quiet = "silent" in shape_text or "no packets" in shape_text
            return Answer(
                probabilities=probs,
                top=top,
                confidence=0.7,
                intensity=0.05 if quiet else 0.5,
                interactivity=0.5,
                nouls={"just_started": 0.1, "just_ended": 0.1, "automated": 0.5, "someone_is_typing": 0.1},
                latency_s=0.05,
            )
        finally:
            self._busy.discard(vif)
